[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
create-token = { path = "../programs/minter" }
anchor-client = "0.30.1"
anyhow = "1.0.86"
shellexpand = "3.1.0"
solana-sdk = "2.0.3"
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["metadata"] }
